Warning: no DISPLAY environment variable.
--No graphics will be displayed.
Traceback (most recent call last):
  File "calc_posterior_and_sample.py", line 185, in <module>
    main(sys.argv[1:])
  File "calc_posterior_and_sample.py", line 130, in main
    file_writer2.save_all(posterior, prior, theta=theta, x =x, x_without=x_without, fig=None, start_time=start_time, finish_time=finish_time)
  File "/mnt/qb/home/macke/kanderer29/sbi_for_eeg_data/code/data_load_writer/write_to_file.py", line 125, in save_all
    self.save_meta(start_time, finish_time)
  File "/mnt/qb/home/macke/kanderer29/sbi_for_eeg_data/code/data_load_writer/write_to_file.py", line 112, in save_meta
    json.dump(json_dict, f)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/macke/kanderer29/.conda/envs/sbi_env/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Flow is not JSON serializable
